import type { NextPage } from "next";
import Head from "next/head";
import { Flex, Heading, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yoel Kiflezghi · Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yoelio_logo.png" />
      </Head>
      <Flex maxW="5xl" mx="auto" h="75vh" direction="column" justifyContent="center">
        <Heading as="h1" fontSize="2xl">
          Hey there! I'm-
          <Text as="span" fontSize={["5xl", "6xl", "8xl"]} color="blue" fontWeight="black" display="block">
            <Text as="span" display="block" color="inherit">
              Yoel
            </Text>
            Kiflezghi.
          </Text>
        </Heading>
        <Text fontSize="xl">
          Software Engineer.
          <Text as="span" variant="secondary">
            &nbsp;Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis praesentium molestias optio
            quaerat. Odit ex id illo laudantium ipsum fuga veritatis sunt impedit nisi, unde facilis, officia dolore
            autem. Quo.
          </Text>
        </Text>
      </Flex>
    </>
  );
};

export default Home;
