import type { NextPage } from "next";
import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yoel Kiflezghi · Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yoelio_logo.png" />
      </Head>
      <Box maxW="5xl" mx="auto" px={[2]}>
        <Text as="h1" fontSize="4xl">
          Hello! I'm-
        </Text>
        <Text fontSize="6xl" color="blue" fontWeight="thin">
          Yoel Kiflezghi
        </Text>
        <Box bg="base.2" borderRadius={4}>
          <Text color="base.01">hi</Text>
        </Box>
      </Box>
    </>
  );
};

export default Home;
