import type { NextPage } from "next";
import Head from "next/head";
import { Box, Flex, Text } from "@chakra-ui/react";
import { Header, HeaderGroup } from "@yoelio/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yoel Kiflezghi · Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yoelio_logo.png" />
      </Head>
      <Header>
        <HeaderGroup>
          <Text>Logo here</Text>
        </HeaderGroup>
      </Header>
      <Box as="main">
        <Flex as="section" id="hero" maxW={"5xl"} mx="auto" px={4} mt={36} direction="column">
          <Text textStyle="body" fontWeight="light">
            Hey there! I&apos;m-
          </Text>
          <Flex as="h1" textStyle="h1" direction="column" mt={2}>
            <Text as="span">Yoel</Text>
            <Text as="span" color="cyan">
              Kiflezghi.
            </Text>
          </Flex>
          <Text textStyle="headline" mt={8}>
            Software Engineer.
            <Text as="span" variant="secondary">
              &nbsp;Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis praesentium molestias optio
              quaerat.
            </Text>
          </Text>
        </Flex>
        <Flex
          as="section"
          id="experience"
          maxW="5xl"
          mx="auto"
          px={4}
          mt={[12, 48]}
          direction="column"
          justifyContent="center"
        >
          <Text textStyle="h2">Experience</Text>
        </Flex>
      </Box>
    </>
  );
};

export default Home;
